# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aKGkbbGHQyuxKxdGryv_cFvSZMgVqzT-
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns

data = pd.read_excel(r'EHRdataSample.xlsx')
print(data.head())

corr = data.corr()
ax = sns.heatmap(corr)

group1 = data.groupby(['Age_Group'])
plt.title('Mental Status')
group1.Anxiety.sum().plot(kind='line', figsize=(10, 4))
group1.Stress.sum().plot(kind='line')
group1.PTSD.sum().plot(kind='line')
group1.Sleep.sum().plot(kind='line')
group1.Depression.sum().plot(kind='line')
plt.legend()